version: "2"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - redis
      - amq
    links:
      - "redis"
      - "amq"
    networks:
      - backend
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
      - "64919:64919"
    command: redis-server
    networks:
      - backend
  # amq:
  #   build:
  #     context: .
  #     dockerfile: amq-docker
  #   ports:
  #     - "5672:5672"
  #   networks:
  #     - backend
  amq:
    image: rabbitmq:latest
    ports: 
      - "5672:5672"
    command: rabbitmq-server start
    networks:
      - backend
networks:
  backend:
    driver: "bridge"
